# pipline:
#   build:
#     image: java:3.5-jdk-${JAVA_VERSION}-alpine
#     environment:
#       - GRADLE_USER_HOME=~/.gradle
#     commands:
#       - ./gradlew test
  
# matrix:  
#   JAVA_VERSION:
#     - 8
#     - 7
# pipline:
#  build:
#     image: java:openjdk-7
#     environment:
#       - GRADLE_USER_HOME=~/.gradle
#     commands:
#       - ./gradlew test

pipeline:
  build:
    #image: java:3.5-jdk-${JAVA_VERSION}-alpine
    # image: java:openjdk-7
    image: maven:3-jdk-8
    pull: true
    commands:
      - mvn clean
      - mvn install
      - mvn deploy

matrix:  
  JAVA_VERSION:
    - 8
    - 7