# pipline:
#   build:
#     image: java:3.5-jdk-${JAVA_VERSION}-alpine
#     environment:
#       - GRADLE_USER_HOME=~/.gradle
#     commands:
#       - ./gradlew test
  
# matrix:  
#   JAVA_VERSION:
#     - 8
#     - 7
# pipline:
#  build:
#     image: java:openjdk-7
#     environment:
#       - GRADLE_USER_HOME=~/.gradle
#     commands:
#       - ./gradlew test

pipeline:
  build:
    image: 3.3.9-jdk-7
    pull: true
    commands:
      - mvn clean
      - mvn install
      - mvn deploy

